# Generated by Django 4.2.19 on 2025-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='clock_speed',
            field=models.IntegerField(blank=True, help_text='Clock speed of GPU, MHz', null=True, verbose_name='Base clock speed'),
        ),
    ]
