# Generated by Django 4.2.19 on 2025-02-18 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0002_alter_gpu_clock_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepclisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpucoolerlisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpulisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpulisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboardlisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psulisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ramlisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagelisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date listed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PC name'),
        ),
    ]
