# Generated by Django 4.2.19 on 2025-02-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0003_casepclisting_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casepclisting',
            options={'verbose_name': 'PC case listing', 'verbose_name_plural': 'PC case listings'},
        ),
    ]
