# Generated by Django 4.2.19 on 2025-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0004_alter_casepclisting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(choices=[('ddr', 'DDR'), ('ddr2', 'DDR2'), ('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], default='ddr4', max_length=30, verbose_name='RAM type'),
        ),
    ]
