# Generated by Django 4.2.19 on 2025-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0005_motherboard_ram_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rambuild',
            options={'verbose_name': 'RAM stick', 'verbose_name_plural': 'RAM sticks'},
        ),
        migrations.AlterModelOptions(
            name='storagebuild',
            options={'verbose_name': 'Storage device', 'verbose_name_plural': 'Storage devices'},
        ),
        migrations.AlterField(
            model_name='cpu',
            name='base_clock_speed',
            field=models.IntegerField(blank=True, help_text='Base clock speed of CPU, GHz', null=True, verbose_name='Base clock speed'),
        ),
    ]
