# Generated by Django 4.2.19 on 2025-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0006_alter_rambuild_options_alter_storagebuild_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='base_clock_speed',
            field=models.FloatField(blank=True, help_text='Base clock speed of CPU, GHz', null=True, verbose_name='Base clock speed'),
        ),
    ]
