# Generated by Django 4.2.19 on 2025-02-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0007_alter_cpu_base_clock_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rambuild',
            options={'verbose_name': 'RAM stick for a build', 'verbose_name_plural': 'RAM sticks for a build'},
        ),
        migrations.AlterModelOptions(
            name='storagebuild',
            options={'verbose_name': 'Storage device for a build', 'verbose_name_plural': 'Storage devices for a build'},
        ),
    ]
