# Generated by Django 4.2.19 on 2025-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0008_alter_rambuild_options_alter_storagebuild_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casepclisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='casepclisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cpucoolerlisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cpucoolerlisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cpulisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cpulisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='gpulisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='gpulisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='motherboardlisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='motherboardlisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='psulisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='psulisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='ramlisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ramlisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='storagelisting',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='storagelisting',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of units', verbose_name='quantity'),
        ),
    ]
