# Generated by Django 4.2.19 on 2025-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0010_alter_casepclisting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_num',
            field=models.IntegerField(verbose_name='Phone number'),
        ),
    ]
