# Generated by Django 4.2.19 on 2025-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0015_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuildlisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
    ]
