# Generated by Django 4.2.19 on 2025-02-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0018_alter_pcbuildlisting_pc_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuildlisting',
            name='pc_build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuildlisting', to='pcportal.pcbuild'),
        ),
        migrations.AlterField(
            model_name='pcbuildlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuildlisting', to='pcportal.seller'),
        ),
    ]
