# Generated by Django 4.2.19 on 2025-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0019_alter_pcbuildlisting_pc_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepclisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='cpucoolerlisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='cpulisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='gpulisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='motherboardlisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='psulisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='ramlisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='storagelisting',
            name='expiration_date',
            field=models.DateField(default='2100-01-01', verbose_name='Expiration date'),
        ),
    ]
