# Generated by Django 4.2.19 on 2025-02-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcportal', '0022_alter_cpucooler_fan_size_alter_cpucooler_max_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbuild_listing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pcportal.pcbuildlisting')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
