# Generated by Django 4.2.19 on 2025-02-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0023_userlikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlikes',
            options={'verbose_name': 'User like', 'verbose_name_plural': 'User likes'},
        ),
    ]
