# Generated by Django 4.2.19 on 2025-02-23 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcportal', '0024_alter_userlikes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='pcbuild_listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pcportal.pcbuildlisting'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
