# Generated by Django 4.2.19 on 2025-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcportal', '0027_alter_casepclisting_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuildlisting',
            name='expiration_date',
            field=models.DateField(default='2025-03-20', verbose_name='Expiration date'),
        ),
    ]
